spring:
  application:
    name: springCloud-Server2
  security:
    user:
      name: user
      password: password123
server:
  port: 8762
eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://user:password@peer3:8763/eureka/  #注册到地址为peer3端口号为8763的eureka服务上