# 开启基于HTTP basic的认证
spring:
  security:
    user:
      name: user                        # 配置登录的账号是user
      password: password123             # 配置登录的密码是password123
  application:
    name: springCloud-Server2
#  profiles: peer3
#配置系统的hosts，windows系统的hosts文件路径：C:\windows\System32\diver\etc\hosts; Linux及MacOs等的是/etc/hosts
#127.0.0.1  peer1  peer2  peer3
#---
#spring:
#  profiles: peer3 #当指定peer1时，主机名是peer1
server:
  port: 8762                    # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: peer2
  client:
    #    registerWithEureka: false    #是否将自己注册到eureka上
    #    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:password123@peer1:8761/eureka/      #将自己注册到peer2这个eureka上

## 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode

# 参考文档：http://my.oschina.net/buwei/blog/618756