#设置hosts配置 在127.0.0.1 后面配置名称peer1 peer2 peer3
#单点eureka服务
server:
  port: 8761
spring:
  application:
    name: springCloud-Server1
  security:
    user:
      name: user
      password: password123
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#turbine:
#  app-config: springCloud-Consumer1,springCloud-Consumer2
#  cluster-name-expression: "'default'"
sidecar:
  port: 8060                                      # Node.js微服务的端口
  health-uri: http://localhost:8060/health.json
eureka:
  client:
      register-with-eureka: false #不将自己注册到eureka服务（高可用配置时不用设置）
      fetch-registry: false
      service-url:
        defaultZone: http://user:password@${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: peer1
  server:
    eviction-interval-timer-in-ms: 30000 #清理关闭或无效的服务时间间隔默认是60秒生产使用默认
    enable-self-preservation: false #禁用eureka的自我保护模式（一般设置为开启默认开启）