server:
  port: 8089
spring:
  application:
    name: springBoot-adminServer
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@peer1:8761/eureka/
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
        health:
          show-details: always






