#基于哪个镜像创建
FROM anImage:tag
#设置环境变量
ENV enviromentValue=value
#设置一个作者签名
MAINTAINER name emmailaddress
#执行的命令
ENTRYPOINT ['java','-jar','xxx.jar']
CMD java -jar /.../xxx.jar  --enviromentValue=value
#copy命令
COPY /filename /directory/filename
#设置对外端口
EXPOSE 8080