server:
  port: 8001
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.springframework.cloud.commons.util.InetUtils: TRACE   # 开启这边的日志，可以打印出Spring查找网卡的过程
    org.springframework.cloud.sleuth: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@peer1:8761/eureka/
  instance:
    prefer-ip-address: true
#    ip-address: 127.0.0.1 #手动指定ip地址
spring:
  cloud:
    inetutils:
        #use-only-site-local-interfaces: true #只使用站点本地地址
        preferred-networks: #使用正则表达式指定使用的网络地址
                - 192.168
                - 10.1
        ignored-interfaces:   #忽略指定名称的网卡
                - docker0
                - veth.*
  application:
      name: springCloud-provider
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的数据脚本
