server:
  port: 8001
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    #整合sleuth
    root: info
    org:
      springframework:
        web:
          servlet:
            DispatcherServley: debug
            #整合sleuth结束
        cloud: DEBUG
          sleuth: DEBUG
        boot: DEBUG
          commons:
            util:
              InetUtils: TRACE
      hibernate: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
              BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@peer1:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10 #续约更新时间默认30秒生产使用默认
    lease-expiration-duration-in-seconds: 30 #续约到期时间默认90秒生产使用默认
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    appname: springCloud-Provider #与spring.application.name配置效果一样两个配置一个就可以
#    ip-address: 127.0.0.1 #手动指定ip地址
spring:
  cloud:
    inetutils:
        #use-only-site-local-interfaces: true #只使用站点本地地址
        preferred-networks: #使用正则表达式指定使用的网络地址
                - 192.168
                - 10.1
                - 127.0
        ignored-interfaces:   #忽略指定名称的网卡
                - docker0
                - veth.*
  application:
      name: springCloud-provider
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的数据脚本
