server:
  port: 8763
spring:
  application:
    name: springCloud-Server3
  security:
    user:
      name: user
      password: password123
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://user:password123@peer2:8762/eureka/  #注册到地址为peer2端口号为8762的eureka服务上